# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-RSS-Timing
version:      1.07
version_from: lib/XML/RSS/Timing.pm
installdirs:  site
requires:
    Carp:                          0
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
